#!/bin/sh
#
# rotate-to-s3        move logs to s3 at shutdown
#
# chkconfig: - 01 01
# description: move logs to s3 at shutdown
#
# Provides:          rotate-to-s3
# X-Stop-After:      $nginx
# Default-Stop:      0 1 6
# Short-Description: rotate-to-s3
# Description:       Calls python script to rotate logs to AWS S3
#
#   Copyright 2012 Corsis
#   http://www.corsis.com/
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
/opt/corsis/bin/rotate-to-s3.py
